name: Release workflow for tagged versions
on:
  release:
    types:
      - created

jobs:
  push-store-image:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pgversion: ['12', '13', '14', '15', '16']
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build pgbuilder image'
        run: |
          cd pgbuilder
          docker build . --build-arg="PGVERSION=${{ matrix.pgversion }}" --tag builder
          docker tag builder ghcr.io/mannemsolutions/pgbuilder:${{ matrix.pgversion }}
          docker tag builder ghcr.io/mannemsolutions/pgbuilder:${{ matrix.pgversion }}-${{ github.ref_name }}

      - name: 'Tag latest'
        run: |
          docker tag builder ghcr.io/mannemsolutions/pgbuilder:latest
          docker tag builder ghcr.io/mannemsolutions/pgbuilder:${{ github.ref_name }}
        if: ${{ matrix.pgversion == '16' }}

      - name: 'Push to ghcr.io'
        run: docker push -a ghcr.io/mannemsolutions/pgbuilder
